services:
  - type: web
    name: weather-api
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql://weatherdb_yux6_user:iPJ4kK0aqFG7avq2Sybgvkjfk5Nvk9Zz@dpg-d0llj0ggjchc73f6mhu0-a/weatherdb_yux6